
/*-----------------SERVICE POST----------------------*/
export const postActionType = {
    FETCH_POST: 'FETCH_POST',
    FETCH_POSTBYID: 'FETCH_POSTBYID',
    DELETE_POSTBYID: 'DELETE_POSTBYID',
    DELETE_SERVICE_POSTBYID: 'DELETE_SERVICE_POSTBYID',
    INSERT_POST: 'INSERT_POST',
    UPDATE_POST: 'UPDATE_POST',
    FETCH_POSTBYCATEGORY: 'FETCH_POSTBYCATEGORY',
   /*-----------------OWNER GET ALL POST----------------------*/

    FETCH_OWNER_GET_ALLPOST: 'FETCH_OWNER_GET_ALLPOST',
    FETCH_OWNER_GET_ALLPOST_PENDING: 'FETCH_OWNER_GET_ALLPOST_PENDING',
    FETCH_OWNER_GET_ALLPOST_DRAFT: 'FETCH_OWNER_GET_ALLPOST_DRAFT',

    /*-----------------OWNER GET ALL Service POST----------------------*/

    FETCH_OWNER_GET_ALL_SERVICE_POST: 'FETCH_OWNER_GET_ALL_SERVICE_POST',
    FETCH_OWNER_GET_ALL_SERVICE_POST_PENDING: 'FETCH_OWNER_GET_ALL_SERVICE_POST_PENDING',
    FETCH_OWNER_GET_ALL_SERVICE_POST_DRAFT: 'FETCH_OWNER_GET_ALL_SERVICE_POST_DRAFT'
};

    /*-----------------PROJECT POST----------------------*/
export const projectPostActionType = {
    FILTER_POST_LIKES:"FILTER_POST_LIKES",
    FETCH_PROJECTPOST: 'FETCH_PROJECTPOST',
    FETCH_PROJECTPOST_BY_ID: 'FETCH_PROJECTPOST_BY_ID',
    FETCH_PROJECTPOST_BY_CATEGORY: 'FETCH_PROJECTPOST_BY_CATEGORY',
    DELETE_PROJECTPOST: 'DELETE_PROJECTPOST',
    INSERT_PROJECTPOST: 'INSERT_PROJECTPOST',
    UPDATE_PROJECTPOST: 'UPDATE_PROJECTPOST',
};

    /*-----------------CATEGORY----------------------*/
export const categoryActionType = {
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    FETCH_CATEGORY_BY_ID: 'FETCH_CATEGORY_BY_ID',
    INSERT_CATEGORY: 'INSERT_CATEGORY',
};
    /*-----------------Account----------------------*/
export const accountActionType = {
    FETCH_FREELANCER_BY_ID: 'FETCH_FREELANCER_BY_ID',
    FETCH_BUSINESSOWNER_BY_ID: 'FETCH_BUSINESSOWNER_BY_ID',
    DELETE_ACCOUNT:'DELETE_ACCOUNT',
};

    /*-----------------FREELANCER ACCOUNT---------------*/
export const flAccountActionType = {
    FETCH_FLACCOUNT_BY_ID: 'FETCH_FLACCOUNT_BY_ID',
    DELETE_fLACCOUNT_BY_ID: 'DELETE_fLACCOUNT_BY_ID',
    UPDATE_FLACCOUNT: 'UPDATE_FLACCOUNT',
};

