import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
        km: {
                overview: "ទិដ្ឋភាពទូទៅ",
                project: "គម្រោង",
                freelancer: "អ្នកឯករាជ្យ",
                aboutUs: "អំពី​ពួក​យើង",
                search: "ស្វែងរក",
                searchFree : "ស្វែងរកសេវាកម្មរបស់ Freelancer",
                searchBu : "ស្វែងរកគម្រោងរបស់ client",
                dashboard: "ផ្ទាំងគ្រប់គ្រង",
                postProject: "ផុសគម្រោង",
                categories: "ប្រភេទ",
                all: "ទាំងអស់",
                title: "ភាសាខ្មែរ",
                message: "សារ",
                login: "ចូលប្រើ",
                register: "ចុះឈ្មោះ",
                myfeeds: "គម្រោងរបស់អតិថិជន",
                postService: "ផុសសេវាកម្ម",
                exploreTheCategories: "ស្វែងរកពីប្រភេទពេញនិយម",
                desInHomepage: "ដំណោះស្រាយអាជីវកម្មសម្រាប់អតិថិជន និង Freelancer ដែលមានបំណងផ្តល់សេវាកម្មល្អបំផុត ជាយុទ្ធសាស្រ្តឈ្នះឈ្នះរវាងអ្នកប្រើប្រាស់​ នឹងអ្នកបង្កើតសេវាកម្ម ។ ចុះឈ្មោះដើម្បីផុសនូវគម្រោងរបស់អ្នក ឬ​ បង្កើនអាជីវកម្មរបស់អ្នក ",
                forFreelancer: "សម្រាប់​ Freelancer",
                desFreelacerHomepage: "គុណសម្បត្តិធំបំផុតមួយនៃការធ្វើការដោយឯករាជ្យក្នុងនាមជាអ្នកឯករាជ្យគឺមានសេរីភាពក្នុងការជ្រើសរើសអតិថិជននិងគម្រោងដោយគ្មានការរឹតត្បិត។ ការងារឯករាជ្យធ្វើឱ្យមនុស្សម្នាក់ងាយស្រួលជ្រើសរើសប្រភេទការងារដោយផ្អែកលើផលប្រយោជន៍និងផលប្រយោជន៍អ្វីដែលល្អបំផុត។ មានភាពបត់បែនធំធេងនៃទីតាំងដែលមានន័យថាយើងអាចធ្វើការនៅគ្រប់ទីកន្លែងហើយលទ្ធភាពគឺគ្មានទីបញ្ចប់។",
                learningMore: "ស្វែងយល់បន្ថែម",
                startFreelacing: "ចាប់ផ្តើម Freelancing",
                benefitOf: "អត្ថប្រយោជន៍នៃ",
                opportunities: "ឱកាសដើម្បីរកប្រាក់ចំណូលបន្ថែម",
                choosetheRightClient: "ជ្រើសរើសអតិថិជននិងគម្រោងត្រឹមត្រូវ",
                immenseFlexibility: "ភាពបត់បែនដ៏ធំ & ពហុមុខ",
                exposure: "ការ​ប៉ះពាល់",
                forClient: "សម្រាប់អតិថិជន",
                desForClient: "កម្លាំងពលកម្មសព្វថ្ងៃកំពុងវិវត្តក្នុងល្បឿនមួយដែលមិនគួរឱ្យជឿ។ ខណៈពេលដែលអ្នកជំនាញកាលពីម្សិលមិញជាថ្ងៃធ្វើការ ៨ ម៉ោងបច្ចុប្បន្នកម្មករសម័យថ្មីមានការរៀបចំការងារដែលអាចបត់បែនបាន។ ធ្វើការជាមួយអ្នកឯករាជ្យផ្តល់នូវសក្តានុពលរីកចម្រើនជាច្រើនសម្រាប់អាជីវកម្មព្រោះវាមានប្រសិទ្ធភាពចំណាយនិងងាយស្រួល",
                clientLearnMore: "ស្វែង​យល់​បន្ថែម",
                startHiring: "ចាប់ផ្តើមជួល",
                startWorking: "ចាប់ផ្តើមធ្វើការ",
                benefits: "អត្ថប្រយោជន៍",
                hiring: "ជួល",
                flexibilityTopSelection: "ភាពបត់បែន & ការជ្រើសរើសថ្នាក់កំពូល",
                costEffectiveOutcome: "លទ្ធផលចំណាយប្រកបដោយប្រសិទ្ធភាព",
                betterWorkQuality: "គុណភាពការងារកាន់តែប្រសើរ៖",
                client: "អតិថិជន",
                sahakka: "សហការណ៍",
                thatAreBestForYou: "ដែលល្អបំផុតសម្រាប់អ្នក",
                desInFeedBusiness: "នេះគឺជាផ្ទាំងព័ត៌មានគម្រោងរបស់អ្នកដែលអ្នកអាចបង្កើតនិងគ្រប់គ្រងរាល់ប្រកាសគម្រោងរបស់អ្នក។ ស្ថានភាពប្រកាសគម្រោងរបស់អ្នកនឹងត្រូវបានបែងចែកជាបីប្រភេទដូចជាសេចក្តីព្រាងដែលអាចមើលឃើញនិងមើលមិនឃើញ។",
                postProject: "ផុសគម្រោង",
                welcome: "សូមស្វាគមន៍",
                projectDashboard: "ផ្ទាំងគ្រប់គ្រងគម្រោង",
                project: "គម្រោង",
                pending: "ផុតថ្ងៃកំណត់",
                draft: "ព្រាង",
                personalInfo: "ព័ត៌មាន​ផ្ទាល់ខ្លួន",
                personalInfoDis: "សូមប្រាប់យើងអំពីខ្លួនអ្នក។ ដើម្បីធានាថា អ្នកអាចបង្កើតទម្រង់អាជីព ដំណើរការត្រូវតែបញ្ចប់ ។",
                fullName: "ឈ្មោះ​ពេញ",
                nationality: "សញ្ជាតិ",
                nation: "ជនជាតិ",
                gender: "ភេទ",
                male: "ប្រុស",
                Famale: "ស្រី",
                address: "អាស័យដ្ឋាន",
                contactInfo: "ព័ត៌មានទំនាក់ទំនង",
                contactInfoDis: "ព័ត៌មានទំនាក់ទំនងរបស់អ្នកនឹងផ្តល់ឱ្យអតិថិជនរបស់អ្នកនូវវិធីសាស្រ្តផ្សេងទៀតក្នុងការទាក់ទងអ្នក។",
                telephone: "លេខទូរស័ព្ទ",
                officailEmail: "អ៊ីមែលផ្លូវការ",
                website: "គេហទំព័រ",
                facebookAccount: "គណនី Facebook ",
                telegramAccount: "គណនី Telegram ",
                TwitterAccount: "គណនី Twitter ",
                linkInAccount: "គណនី LinkIn ",
                companyInfor: "ព័ត៌មាន​ក្រុមហ៊ុន",
                companyName:"ឈ្មោះក្រុមហ៊ុន",
                companyInforDis: "ពត៌មានរបស់ក្រុមហ៊ុនពិតជាមានសារៈសំខាន់ព្រោះវានឹងក្លាយជាធនធានដើម្បីបញ្ជាក់ថាភាពដូចគ្នាមានស្របច្បាប់ ការផ្តល់ព័ត៌មាននេះនឹងអនុញ្ញាតឱ្យអ្នកឯករាជ្យមានការពិតច្រើនជាងធ្វើការជាមួយបុគ្គលអនាមិក ។",
                cancel: "បោះបង់",
                update: "កែប្រែ",
                delete: "លុប",
                companyInfo: "អំពីក្រុមហ៊ុន",
                accountSetting: "ការកំណត់​គណនី",
                deactivateAccount: "បិទ​ដំណើរការ​គណនី",
                email: "អ៊ីមែល",
                password: "ពាក្យសម្ងាត់",
                forgotPassword: "ភ្លេច​លេខសំងាត់ ?​",
                deactivate: "បិទ​ដំណើរការ",
                resetPassword: "កំណត់ពាក្យសម្ងាត់ឡើងវិញ",
                oldPassword: "លេខសំងាត់​ចាស់",
                newPassword: "ពាក្យសម្ងាត់​ថ្មី",
                confirmPassword: "បញ្ជាក់លេខសំងាត់",
                enterOldPassword: "បញ្ចូលលេខសំងាត់​ចាស់",
                enterNewPassword: "បញ្ចូលពាក្យសម្ងាត់​ថ្មី",
                pleaseConfirmPassword: "សូមបញ្ជាក់លេខសំងាត់",
                chooseImage: "ជ្រើសរើសរូបភាព",
                chooseProfile:"ជ្រើសរើសប្រូហ្វាល់",
                additionalInformation: "ព័​ត៍​មាន​បន្ថែម",
                projectTitle: "ចំណងជើងអត្ថបទ",
                enterYourProjectTitle: "បញ្ចូលចំណងជើងគម្រោងរបស់អ្នក",
                selectCategories: "ជ្រើសរើសប្រភេទ",
                selectDeadline: "ជ្រើសរើសកាលបរិច្ឆេទ",
                projectDesc: "ការពិពណ៌នាគម្រោង",
                post: "ផុស",
                selectRelatedCategories: "ជ្រើសរើសប្រភេទដែលពាក់ព័ន្ធ",
                enterYourProjectDescription: "បញ្ចូលការពិពណ៌នាគម្រោងរបស់អ្នក ....",
                publishedBy: "ចេញផ្សាយ​ដោយ",
                viewProfile: "មើលប្រវត្តិរូប",
                projectDuration: "រយៈពេលគម្រោង",
                publishedDate: "កាលបរិច្ឆេទចេញផ្សាយ",
                deadLine: "ផុតកំណត់",
                location: "ទីតាំង",
                like: "ចូលចិត្ដ",
                comments: "យោបល់",
                reviews: "ពិនិត្យឡើងវិញ",
                posted: "បានប្រកាស",
                projectBudget: "ថវិកាគម្រោង",
                duration: "រយៈពេល៖",
                links: "តំណភ្ជាប់",
                language: "ភាសា",
                dateOfBirth: "ថ្ងៃខែ​ឆ្នាំ​កំណើត",
                expertiseDetail: "លម្អិតជំនាញ",
                expertiseAndBackground: "ជំនាញ និង ប្រវត្តិ",
                expertiseAndBackgroundDis: "ត្រូវប្រាកដថា បានបញ្ចូលប្រវត្តិសិក្សា ជីវប្រវត្តិជំនាញ និង បទពិសោធន៍ការងារដែលពាក់ព័ន្ធរបស់អ្នក ។ ទាំងនេះនឹងជួយអ្នកឱ្យលេចធ្លោ​​ និង ធ្វើឱ្យទម្រង់របស់អ្នកមានលក្ខណៈវិជ្ជាជីវៈ។",
                skill: "ជំនាញ",
                enterYourSkill: "បញ្ចូលជំនាញរបស់អ្នក",
                enterYourBio: "បញ្ចូល Bio របស់អ្នក",
                enterYourEduBackground: "បញ្ចូលប្រវត្តិការសិក្សារបស់អ្នក",
                educationalBackground: "ប្រវត្តិការសិក្សា",
                experienceAndAchievement: "បទពិសោធន៍​ និង សមិទ្ធផល",
                experienceAndAchievementDis: "ត្រូវប្រាកដថា បានបញ្ចូលប្រវត្តិសិក្សាជីវប្រវត្តិជំនាញ​ និង បទពិសោធន៍ការងារដែលពាក់ព័ន្ធរបស់អ្នក ។ ទាំងនេះនឹងជួយអ្នកឱ្យលេចធ្លោ និង ធ្វើឱ្យទម្រង់របស់អ្នកមានលក្ខណៈវិជ្ជាជីវៈ ។",
                workExperience: "បទពិសោធន៍​ការងារ",
                enterYourWorkExp: "បញ្ចូលបទពិសោធន៍ការងាររបស់អ្នក",
                achievement: "សមិទ្ធផល",
                enterYourAchievement: "បញ្ចូលសមិទ្ធផលរបស់អ្នក",
                freelancerFeedDesc: "សូមរីករាយស្វែងយល់ពីអតិថិជននិងគម្រោងដែលសមស្របបំផុតសម្រាប់អ្នកសង្ឃឹមថាអ្នកនឹងរីករាយជាមួយអ្វីដែលអស្ចារ្យនៅទីនេះ។ ត្រូវប្រាកដថាអាចទៅដល់ប្រសិនបើមានអ្វីដែលទាក់ទងនឹងអ្នក។",
                myCategories: "ប្រភេទរបស់នៃគម្រោង",
                myProfile: "ប្រវត្តិរូបរបស់ខ្ញុំ",
                editCategory: "កែសម្រួលប្រភេទ",
                experiences: "បទពិសោធន៍",
                serviceCardDashboard: "ផ្ទាំងព័ត៌មានកាតសេវាកម្ម",
                serviceCards: "កាតសេវាកម្ម",
                serviceCardPost: "ផុសកាតសេវាកម្ម",
                serviceCardTitle: "ឈ្មោះកាតសេវាកម្ម",
                enterYourCardTitle: "បញ្ចូលឈ្មោះកាតរបស់អ្នក",
                cardDesc: "ការពិពណ៌នាកាត",
                enterYourServiceCardDesc: "បញ្ចូលការពិពណ៌នាកាតសេវាកម្មរបស់អ្នក ....",
                hereAretheResult: "នេះគឺជាលទ្ធផល",
                serviceAvailable: "សេវាកម្មដែលមាន",
                projectAvailable: "គម្រោងដែលមាន",
                addComment: "បញ្ចេញមតិ",
                termOfService: "រយៈពេលនៃសេវាកម្ម",
                privacyPolicy: "លក្ខខណ្ឌ​នៃ​សេវាកម្ម",
                faq: "សំណួរនិងចម្លើយ",
                support: 'រកជំនួយ',
                discover: "រកឃើញ",
                contactUs: "ទំនាក់ទំនង​ ពួកយើង",
                footerDis: "ស្វែងយល់ពីគម្រោងដែលអ្នកចង់បាន ហើយស្វែងរកអ្នកជំនាញ ដែលមានជំនាញគ្រប់គ្រាន់ ។ សហការ គឺ ជាជម្រើសដ៏ល្អ សម្រាប់អ្នក ។",
                copyRight: "២០២១​ រក្សាសិទ្ធ គ្រប់យ៉ាងដោយ សហការ",
                welcomeTo: "សូមស្វាគមន៍​​ មកកាន់​ ",
                ourStory: "អំពី​ ពួក​យើង",
                ourMission: "បេសកម្ម របស់ពួកយើង",
                ourVision: "ចក្ខុវិស័យ របស់ពួកយើង",
                ourStoryDis: "យើងនឹងព្យាយាមធ្វើសមាហរណកម្មនិងចិញ្ចឹមសេដ្ឋកិច្ចកម្ពុជាទៅក្នុងសក្ដានុពលថ្មីនៃវប្បធម៌ការងារបច្ចុប្បន្ននិងវិធីសាស្រ្តថ្មីៗសម្រាប់សកម្មភាពអាជីវកម្ម។ យើងខិតខំផ្តល់លទ្ធភាពនិងគាំទ្រដល់ប្រជាជនកម្ពុជាដើម្បីបង្កើនប្រាក់ចំណូលនិងភាពញឹកញាប់សម្រាប់សកម្មភាពអាជីវកម្មរបស់ពួកគេតាមរយៈការអនុវត្តរចនាសម្ព័ន្ធថ្មីៗដែលអាចលើកកម្ពស់ស្តង់ដារការងារនិងសកម្មភាពអាជីវកម្ម។ តាមរយៈវេទិកានេះផែនការប្រកបដោយមហិច្ឆតារបស់យើងនឹងស្វែងរកដើម្បីជួយសម្រួលនិងបង្កើតមូលដ្ឋានគ្រឹះសម្រាប់បង្កើនសកម្មភាពអាជីវកម្មនិងប្រតិបត្តិការសម្រាប់អ្នកឯករាជ្យនិងសហគ្រាសធុនតូចនិងមធ្យមនៅក្នុងប្រទេសកម្ពុជានិងណែនាំសង្គមកម្ពុជាឱ្យបង្កើតអ៊ិនធឺរណែតជាឧបករណ៍ច្នៃប្រឌិតថ្មីនិងជាបណ្តាញសម្រាប់អាជីវកម្មងាយស្រួលភ្ជាប់ទំនាក់ទំនងគ្នា។",
                ourMissionDis: "បេសកកម្មរបស់យើងគឺផ្តល់សិទ្ធិអំណាចនិងវិជ្ជាជីវៈដល់កម្លាំងឯករាជ្យនៃប្រទេសកម្ពុជាតាមរយៈការផ្តល់វេទិកាទីផ្សារឯករាជ្យដែលអាចចូលដំណើរការបានប្រកបដោយសុវត្ថិភាពនិងវិចារណញាណ។ ដើម្បីធ្វើឱ្យឯករាជ្យនិងនិយោជិកយកចិត្តទុកដាក់ចំពោះខ្លួនឯងយើងចង់អោយគេបំពាក់នូវបច្ចេកវិទ្យាឧបករណ៍ដែលបានគាំទ្រយ៉ាងល្អ។",
                ourVisionDis: "ចក្ខុវិស័យ របស់ពួកយើង គឺផ្ដល់ឱកាសដល់អ្នកឯករាជ្យនិងអាជីវកម្មខ្នាតតូចដែលនឹងប្រើវេទិការបស់យើងដើម្បីភ្ជាប់ទំនាក់ទំនងជាមួយអតិថិជននិងដៃគូអាជីវកម្មកាន់តែច្រើន។ វេទិកានេះគឺជាការបោះជំហានទៅមុខសម្រាប់ទីផ្សារបណ្តាញកម្លាំងពលកម្មខាងក្រៅនៅក្នុងប្រទេសកម្ពុជា។ អាចផ្តល់នូវមូលដ្ឋានគ្រឹះជំនាញក្នុងការបង្កើតសកម្មភាពអាជីវកម្មដែលពីមុននឹងពឹងផ្អែកលើបណ្តាញប្រពៃណីនិងការតភ្ជាប់នឹងបង្កើនប្រសិទ្ធភាពនិងឱកាសយ៉ាងខ្លាំងសម្រាប់អតិថិជននិងអ្នកឯករាជ្យក្នុងការភ្ជាប់ទំនាក់ទំនងជាមួយគ្នា។",
                ourTeam: "សមាជិក របស់ពួកយើង",
                on: 'នៅក្នុង',
                startFreeIn: 'ចាប់ផ្ដើម Freelancing ក្នង',
                steps: '3 ជំហានងាយៗ ',
                createYourProfile: "បង្កើតប្រវត្តិរូបរបស់អ្នក",
                createYourProfileDis: "បង្កើតទម្រង់អាជីពផ្ទាល់ខ្លួនរបស់អ្នក ដូច្នេះអ្នកអាចបង្ហាញជំនាញនិងបទពិសោធន៍របស់អ្នក",
                exploreProjects: "ស្វែងយល់ពីគម្រោង",
                exploreProjectsDis: "ស្វែងរកអតិថិជននិងគម្រោងដែលសមស្របបំផុតសម្រាប់អ្នក។ នេះគឺជាអ្វីដែលយើងហៅថាសេរីភាពក្នុងឧស្សាហកម្មឯករាជ្យ",
                workEarn: "ធ្វើការ និង រកប្រាក់",
                workEarnDis: "ចាប់ផ្តើមធ្វើការលើគម្រោងដែលអ្នកចង់បានហើយទទួលបានប្រាក់ពីវាកាន់តែច្រើនអ្នកនឹងសម្រេចបានការងារកាន់តែច្រើន",
                loginDis: "សង្ឃឹមថាអ្នកនឹងរីករាយក្នុងការរុករក អ្នកធ្វើការឯករាជ្យ និង គម្រោងដែលអ្នកចង់បាន និង រីករាយជាមួយបទពិសោធន៍ដ៏អស្ចារ្យ ។",
                alreadyHaveAcc: "មានគណនីរូចហើយ ?",
                next: "បន្ទាប់​",
                previous: "ថយក្រោយ",
                createAcc: "បង្កើត គណនី",
                createAccDis: "ចុះឈ្មោះដើម្បីអាចទទួលបាន អ្នកឯករាជ្យដែលមានលក្ខណៈគ្រប់គ្រាន់សម្រាប់គម្រោងរបស់អ្នក ឬ ស្វែងយល់ពីគម្រោងដើម្បីអាចរកលុយតាមដែលអ្នកចង់បាន ។",
                socialMedia: "បណ្ដាញសង្គម",
                signUp: "ចុះ​ឈ្មោះ",
                nodata: "គ្មានទិន្នន័យ",
                logOut: "ចាកចេញ",
                successfullyLogin: "ចូលប្រើប្រាស់ជោគជ័យ",
                successfullyRegister: "ចុះឈ្មោះប្រើប្រាស់ជោគជ័យ",
                khmer: "ភាសាខ្មែរ",
                english: "អង់គ្លេស",
                projectHasBeenCreated: "គម្រោងត្រូវបានបង្កើត",
                serviceHasBeenPosted: "សេវាកម្មត្រូវបានបង្កើត",
                areYouSure: "តើអ្នកប្រាកដឬទេ?",
                yes: "យល់ព្រម",
                no: "ទេ",
                deleted: "ត្រូវបានលុប",
                yourservicehasbeendeleted: "សេវាកម្មរបស់អ្នកត្រូវបានលុប",
                yourprojecthasbeendeleted: "គម្រោងរបស់អ្នកត្រូវបានលុប",
                ok: "យល់ព្រម",
                numSer:'ចំនួននៃកាតសេវាកម្មគឺ',
                postUpdated:'កែប្រែបានជោគជ័យ',
                postCreated:'បង្កើតបានជោគជ័យ',
                keoBio:'សួស្តី ខ្ញុំគឺ កែវ។ ខ្ញុំជានិស្សិតនៃសាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ និងជាសិស្សជំនាន់ទី ៩ នៃមជ្ឈមណ្ឌល Korea Software HRD Center។ បន្ទាប់ពីការស្រាវជ្រាវ និងទទួលបានចំណេះដឹងពីលោកគ្រូ អ្នកគ្រូរបស់យើង យើងទទួលបានគម្រោងមួយនេះដែលមានឈ្មោះថា SAHAKKA។ ខ្ញុំជឿជាក់ថាគម្រោងនេះនឹងជួយច្រើនដល់វិស័យពាណិជ្ជកម្ម។ ខ្ញុំសង្ឃឹមថាអ្នកប្រើប្រាស់នឹងរីករាយ និងបន្តប្រើប្រាស់កម្មវិធីគេហទំព័រនេះ។ សូមអរគុណចំពោះការប្រើប្រាស់ សហការ ។',
                horBio:'សួស្តី! ខ្ញុំគឺ ឈីងហ័រ។ ខ្ញុំបានបញ្ចប់ការសិក្សាពីសាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ ហើយខ្ញុំជាសិស្សជំនាន់ទី ៩ នៃមជ្ឈមណ្ឌល Korea Sofware HRD ។ គម្រោងនេះគ្រាន់តែជាការចាប់ផ្តើមដំបូងរបស់ខ្ញុំ តែខ្ញុំបានរៀនសូត្រច្រើនពីវា។ ខ្ញុំសង្ឃឹមថាវាជួយច្រើន ដល់អ្នកទាំងអស់គ្នា។ នៅពេលគិតពីការធ្វើអាជីវកម្ម បែប Freelance អ្នកប្រើប្រាស់នឹងនឹកឃើញ វេបសាយ សហការ មុនគេ។ សូមអរគុណ!',
                titBio:'ខ្ញុំឈ្មោះ សេងទិត្យ ជានិស្សិតនៃសាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ និងជានិស្សិតជំនាន់ទី ៩ នៃមជ្ឈមណ្ឌល Korea Software HRD ។ ខណៈពេលធ្វើគម្រោងនេះ យើងបានឆ្លងកាត់រឿងជាច្រើន ដើម្បីធ្វើឱ្យវាដំណើរការ។ ទោះយ៉ាងណាក៏ដោយ យើងបានសំរេចគម្រោងនេះ ហើយខ្ញុំសង្ឃឹមថាអ្នកទាំងអស់គ្នាចូលចិត្តវា។ សូមអរគុណនិងសំណាងល្អ។ (^-^)',
                chhorBio:'ខ្ញុំឈ្មោះ គឹមឈ័រ ជាសិស្សជំនាន់ទី ៩ នៃមជ្ឈមណ្ឌល Korea Software HRD Center និងជានិស្សិតនៃសាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ។ បន្ទាប់ពីបញ្ចប់វគ្គសិក្សាមូលដ្ឋាននៅមជ្ឈមណ្ឌល Korea Software HRD Center ខ្ញុំបានរៀនសូត្រច្រើនពីអ្នករាល់គ្នា ជាពិសេសនៅក្នុងគម្រោងនេះ។ ជាការពិតយើងបានខិតខំយ៉ាងខ្លាំងដើម្បីធ្វើឱ្យវេបសាយនេះដំណើរការ ព្រោះយើងបានសហការគ្នា។ ជាចុងក្រោយខ្ញុំសង្ឃឹមថាអ្នកប្រើប្រាស់ទាំងអស់នឹងមិនជួប bug ណាមួយនៅក្នុងកម្មវិធីគេហទំព័រនេះឡើយ xD ។សូមអរគុណ (^,^)',
                sethBio:'ខ្ញុំឈ្មោះ ពិសិទ្ធ។ ខ្ញុំជានិស្សិតនៅសាកលវិទ្យាល័យភូមិន្ទភ្នំពេញនិងជានិស្សិតជំនាន់ទី ៩ នៅមជ្ឈមណ្ឌល Korea Software HRD។ ក្រុមរបស់យើងខិតខំធ្វើការដើម្បីបង្កើតគេហទំព័រនេះ ហើយយើងទន្ទឹងរង់ចាំធ្វើការជាមួយគ្នានាពេលអនាគតទៀត។ អ្នកទាំងអស់គ្នាអាចទាក់ទងខ្ញុំបាន បើមានអ្វីអោយខ្ញុំជួយ។ រីករាយដែលបានស្គាល់អ្នក❤️',
                porleasBio:'សួស្តី! ខ្ញុំ ឈ្មោះ ពោលាស់។ ខ្ញុំជានិស្សិតជំនាន់ទី ៩ នៃមជ្ឈមណ្ឌល Korea Software HRD និងជានិស្សិតនៃសាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ។ វាជាបទពិសោធន៍ដ៏ល្អដែលខ្ញុំមានឱកាសធ្វើគម្រោងដ៏អស្ចារ្យនេះ។ វាជាពេលវេលាពិបាកសម្រាប់ខ្ញុំ ប៉ុន្តែខ្ញុំរីករាយនឹងធ្វើវា។ សង្ឃឹមថាអ្នកទាំងអស់គ្នាចូលចិត្តគេហទំព័រនេះ។ សូមអរគុណ',
                signUpClientSuccess:'អ្នកបានបង្កើតគណនីជា Client ជោគជ័យ',
                signUpFlSuccess:'អ្នកបានបង្កើតគណនីជា Freelancer ជោគជ័យ',
                proFileUpdated:"ប្រវត្តិរូបរបស់អ្នកត្រូវបានកែប្រែបានជោគជ័យ",
                disAcc:'គណនីរបស់លោកអ្នកត្រូវបានលុប​ !',
                savTodraf:'សេវាកម្មត្រូវបានរក្សាជាព្រាង',
                companyName:'ឈ្មោះក្រុមហ៊ុន',
                company_description:'ពណ៌នាពីក្រុមហ៊ុន',
                deleteAccSuccess:'គណនីរបស់អ្នកត្រូវបានលុប',
                updateAccSuccess:'គណនីរបស់អ្នកត្រូវបានកែប្រែ',
                wrongPw:'ពាក្យសម្ងាត់របស់លោកអ្នកមិនត្រឹមត្រូវទេ សូមព្យាយាមម្ដងទៀត!',
                validEmail: 'ទម្រង់អុីម៉ែលរបស់អ្នកមិនត្រឹមត្រូវទេ',
                pleaseInPutPassword: 'សូមបញ្ចូលពាក្យសម្ងាត់របស់លោកអ្នក!',
                pleaseInPutEM: 'សូមបញ្ចូលអុីម៉ែលរបស់អ្នក',
                minPassword: 'ពាក្យសម្ងាត់មិនអាចតិចជាង​ 3 ខ្ទង់!',
                maxPassword: 'ពាក្យសម្ងាត់មិនអាចច្រើនជាង ២៥ ខ្ទង់!',
                reportPost: 'រាយការណ៍បានជោគជ័យ',
                reasonWhyReportOn: 'ហេតុអ្វីបានជាអ្នកចង់រាយការណ៍លើផុសនេះ?',
                okButtonReport: 'យល់ព្រម',
                canCelButton: 'បោះបង់',
        },
        en: {
                ok: "OK",
                yourprojecthasbeendeleted: "Your project post has been deleted.",
                deleted: "Deleted!",
                yourservicehasbeendeleted: "Your service post has been deleted.",
                overview: "Overview",
                project: "Project",
                freelancer: "Freelancer",
                aboutUs: "About Us",
                search: "Search",
                searchFree : "Search Freelancer service",
                searchBu : "Search project post ",
                dashboard: "Dashboard",
                postProject: "Post Project",
                categories: "Categories",
                all: "All",
                title: "English",
                message: "Message",
                login: "Login",
                register: "Register",
                myfeeds: "Client`s Project",
                postService: "Post Service",
                exploreTheCategories: "Explore the popular categories",
                desInHomepage: "A business solution for both clients and freelancers aiming to provide the best freelance services as a win-win strategy between the two consumers. Signing up to post your projects and grow your business or to earn from your expertise.",
                forFreelancer: "For Freelancers",
                desFreelacerHomepage: "One of the biggest advantages of working independently as a freelancer is having freedom in choosing clients and projects without any restrictions. Freelancing makes it very simple for a person to choose the type of work based on what interests and benefits them best. Having immense flexibility of locations which means we can work anywhere and the possibility are endless.",
                learningMore: "Learning More",
                startFreelacing: "Start Freelancing",
                benefitOf: "Benefits Of",
                opportunities: "Opportunities To Earn More",
                choosetheRightClient: "Choose The Right Client And Project ",
                immenseFlexibility: "Immense Flexibility & Multi-Faceted",
                exposure: "Exposure",
                forClient: "For Client",
                desForClient: "Today’s workforce is evolving at an unbelievable pace. While yesterday’s professionals used to be an eight-hour workday, modern workers now have more flexible work arrangements. Working with freelancers offers lots of growth potential for business since it is cost-effective and convenient. ",
                clientLearnMore: "Learn More",
                startHiring: "Start Hiring",
                startWorking: "Start working",
                benefits: "Benefits",
                hiring: "Hiring",
                flexibilityTopSelection: "Flexibility & Top-Tier Selection",
                costEffectiveOutcome: "Cost-Effective Outcome",
                betterWorkQuality: "Better Work Quality",
                client: "Client",
                sahakka: "SAHAKKA",
                thatAreBestForYou: "That Are Best For You",
                desInFeedBusiness: "Here is your project's dashboard where you can create and manage all of your project posts. Your project post status will be categorized into three categories such draft, visible and invisible.  ",
                postProject: "Post Project",
                welcome: "Welcome",
                projectDashboard: "Project Dashboard",
                project: "Project",
                pending: "Expired posts",
                draft: "Draft",
                personalInfo: "Personal Information",
                personalInfoDis: 'Please tell us about yourself. To ensure that you can create a professional profile , the process must be completed.',
                fullName: "Full Name",
                nationality: "Nationality",
                nation: "Nation",
                gender: "Gender",
                male: "Male",
                Famale: "Female",
                address: "Address",
                contactInfo: "Contact Information",
                contactInfoDis: "Your contact information will provide your clients other convinient way of contacting you.",
                telephone: "Telephone",
                officailEmail: "Officail Email",
                website: "Website",
                facebookAccount: "Facebook Account",
                telegramAccount: "Telegram Account",
                TwitterAccount: "Twitter Account",
                linkInAccount: "LinkIn Account",
                companyInfor: "Company Information",
                companyName:"Company Name",
                companyInforDis: "Company information is really important , since it will be the resources to clarify that the compony is legitly exist. Providing this information will let freelancers have more truth than working with anonymous figure.",
                cancel: "Cancel",
                update: "Update",
                companyInfo: "Company Info",
                accountSetting: "Account Setting",
                deactivateAccount: "Deactivate Account",
                email: "Email",
                password: "Password",
                forgotPassword: "Forgot password ?",
                deactivate: "Deactivate",
                resetPassword: "Reset Password",
                oldPassword: "Old Password",
                newPassword: "New Password",
                confirmPassword: "Confirm Password",
                enterOldPassword: "Enter Old Password",
                enterNewPassword: "Enter New Password",
                pleaseConfirmPassword: "Please Confirm Password",
                delete: "Delete",
                chooseImage: "Choose Image",
                additionalInformation: "Additional Information",
                projectTitle: "Project Title",
                enterYourProjectTitle: "Enter your project title",
                selectCategories: "Select Categories",
                selectDeadline: "Select Deadline",
                projectDesc: "Project Description",
                post: "Post",
                selectRelatedCategories: "Select related categories",
                enterYourProjectDescription: "Enter your project description....",
                publishedBy: "Published By",
                viewProfile: "View Profile",
                projectDuration: "Project Duration",
                publishedDate: "Published Date",
                deadLine: "Deadline",
                location: "Location",
                like: "Like",
                comments: "Comments",
                reviews: "Reviews",
                posted: "Posted",
                projectBudget: "Project Budget",
                duration: "Duaration",
                links: "Links",
                language: "Language",
                dateOfBirth: "Date Of Birth",
                expertiseDetail: "Expertise Detail",
                expertiseAndBackground: "Expertise & Background",
                expertiseAndBackgroundDis: 'Make sure to include your educational background , bio , expertise and your relavant working experiences . These will help you stand out and make your profile professinal.',
                skill: "Skill",
                enterYourSkill: "Enter your skill",
                enterYourBio: "Enter your Bio",
                enterYourEduBackground: "Enter your Educational Background",
                educationalBackground: "Educational Background",
                experienceAndAchievement: "Experience & Achievement",
                experienceAndAchievementDis: "Make sure to include your educational background , bio , expertise and your relavant working experiences . These will help you stand out and make your profile professinal.",
                workExperience: "Work Experiences",
                enterYourWorkExp: "Enter your Work Experiences",
                achievement: "Achievements",
                enterYourAchievement: "Enter Your Achievement",
                freelancerFeedDesc: "Have fun exploring clients and projects that are best suited for you, hopefully, you will enjoy the great here. Be sure to reach out if there is anything that concerns you.",
                myCategories: "Project`s Categories",
                myFeeds: "Client`s Project",
                myProfile: "My Profile",
                editCategory: "Edit Category",
                experiences: "Experiences",
                serviceCardDashboard: "Service Card Dashboard",
                serviceCards: "Service Cards",
                serviceCardPost: "Service Card Post",
                serviceCardTitle: "Service Card Title",
                enterYourCardTitle: "Enter your card title",
                cardDesc: "Card Description",
                enterYourServiceCardDesc: "Enter your service card description....",
                hereAretheResult: "Here are the result",
                serviceAvailable: "services available",
                projectAvailable: "គម្រោងដែលមាន",
                addComment: "add your comment",
                termOfService: "Terms of Service",
                privacyPolicy: "Privacy Policy",
                faq: "FAQ",
                support: 'SUPPORT',
                discover: "DISCOVER",
                contactUs: "CONTACT US",
                footerDis: "Explore your desired projects and find the qualified freelancers . SAHAKKA is your best choice.",
                copyRight: "2021 Copyright SAHAKKA",
                welcomeTo: "Welcome to ",
                ourStory: "Our Story",
                ourMission: "Our Mission",
                ourVision: "Our Vision",
                ourStoryDis: "we will seek to integrate and nurture the Cambodian economy into the new dynamics of contemporary working culture and the new methods for business activities. We strive to provide access and support for Cambodians to increase income and the frequency for their business activities, through implementing new contemporary structures that can elevate working standards and business activities. Through the platform, our ambitious plans will look to facilitate and create the foundation for increased business activities and transactions for freelancers and SMEs in Cambodia, and introducing the Cambodian society to Online Outsourcing as a new innovative tool and channel for businesses to easily connect with each other.",
                ourMissionDis: "Our mission is to empower and professionalize the freelancing workforce of Cambodia by providing an accessible, secure, and intuitive-to-use freelancing marketplace platform. To make freelancers take themselves seriously and employers take freelancers seriously, we want to equip them with a technological, well-supported tool to showcase their talents and solidify their credibility.",
                ourVisionDis: "Our Vision is giving opportunities to the freelancers and small businesses who will use our platform to connect with more customers and business partners. The platform is a step forward for the Online Outsourcing market in Cambodia. Being able to provide a specialized foundation to creating business activities that previously would rely on traditional networks and connections would significantly increase the efficacy and opportunities for Clients and Freelancers to connect with one another.",
                ourTeam: "Our Team",
                on: 'on',
                startFreeIn: 'Start Freelancing in',
                steps: '3 Simple Steps',
                createYourProfile: "Create your profile",
                createYourProfileDis: "create your own professional profile, so that you can showcase your skills and experties",
                exploreProjects: "Explore Projects",
                exploreProjectsDis: "Find the clients and the projects that are best suited for you.This is what we call freedom in the freelancing industry",
                workEarn: "Work & Earn",
                workEarnDis: "Start working on your desired projects and get paid from it.The more you get the work done that more you earn",
                loginDis: "Hope you will have fun exploring the the freelancers and the projects that you desired and enjoy the wonderful experiences .",
                alreadyHaveAcc: "already has an account ?",
                next: "Next",
                previous: "Previous",
                createAcc: "Create an account",
                createAccDis: "Sign up to be able to get the freelancers that are qualified for your projects or explore the projects to be able to earn lorem you want to be able be able",
                socialMedia: "Social Media",
                signUp: "Sign Up",
                nodata: "No data",
                logOut: "Log out",
                successfullyLogin: "Successfully Login",
                successfullyRegister: "Successfully Register",
                khmer: "Khmer",
                english: "English",
                projectHasBeenCreated: "Project Has Been Created.",
                serviceHasBeenPosted: "Service Has Been Postrd.",
                areYouSure: "Are you sure?",
                yes: "Yes",
                no: "No",
                numSer:'Number of service card is ',
                postUpdated:'Update success',
                postCreated:'Create success',
                keoBio:'My name is Keo . I am a student of Royal University of Phnom Penh and the 9th generation student of Korea Sofware HRD Center. After researching and getting knowledge from our instructors, we get this project called SAHAKKA.  I am sure that this project will help a lot to business sector especially in gig economy. I hope users will enjoy and continue using this web application. Thank you for using SAHAKKA. ',
                horBio:'Hello! I’m Chhinghor. I graduated from Royal University of Phnom Penh and I am the 9th generation student at Korea Sofware HRD Center. This project is just my first start but I learned a lot from it. I hope it will be a great help to all of you. When thinking of freelancing, users might first think of SAHAKKA. Thank you and have a nice day!',
                titBio:'My name is Sengtit, a student of Royal University of Phnom Penh and the 9th generation student of Korea Software HRD Center. While processing this project, we went through a lot to make it happen. Anyway, we made it and I hope all of you like it. Thank you and have a wonderful day. (^-^)',
                chhorBio:'I’m Kimchhor, the 9th generation student of Korea Software HRD Center and a senior student of Royal University of Phnom Penh. After the basic course, I learned a lot from everyone especially within this project. Of course, we worked really hard to make it existed because we SAHAKKA. Last but not least, I hope all of the users won’t face any bugs within this web application xD. Thank you (^,^)',
                sethBio:'My name is Piseth. I am a student at Royal University of Phnom Penh and 9th generation student at Koran Sofware HRD. Our teams work hard for publishe this website and we look forward to working together in the future. Please let me know if I can help with anything , Glad to know you ❤️',
                porleasBio:'Hi there! I’m Porleas. I am the 9th generation student of Korea Software HRD Center and a student of Royal University of Phnom Penh.  It’s such a great experience that I have chance to do this amazing project. It was a hard time for me but I enjoyed doing it. Hope you like it. THANK YOU.',
                signUpClientSuccess:'You created an account as client successfully',
                signUpFlSuccess:'You created an account as freelancer successfully',
                proFileUpdated:"Your Profile has been updated",
                disAcc:'Your account has been updated',
                savTodraf:'Service has been saved as draft',
                companyName:'Company Name',
                company_description:'Company Description',
                chooseProfile:'Choose Profile',
                deleteAccSuccess:'Your account has been deactivated successfully!',
                updateAccSuccess:'Your account has been updated successfully!',
                wrongPw:'Wrong password. Please try again!',
                validEmail: 'The input email is not valid ',
                pleaseInPutEM: 'Please input your email',
                minPassword: 'Password could not be less than 3 digits',
                maxPassword: 'Password could not be more than 25 digits',
                pleaseInPutPassword: 'Plese input your password!',
                reportPost: 'Reported Successfully!',
                reasonWhyReportOn: 'Tell us why you want to report this post ?',
                okButtonReport: 'Ok',
                canCelButton: 'Cancel',
                
        }
});